hl.on("hyprland.start", function ()
  hl.exec_cmd("hyprpaper & waybar & hypridle")
  hl.exec_cmd("wl-paste --watch cliphist store")
  hl.exec_cmd("systemctl --user start hyprpolkitagent.service")
  hl.exec_cmd("$HOME/.config/hypr/scripts/env.sh")
end)
